---
- name: Install SSH, Apache, Python, Flask, and Clone Git repository
  hosts: all
  become: true

  tasks:
    - name: Install SSH server
      package:
        name: openssh-server
        state: present

    - name: Install Apache HTTP Server (httpd)
      package:
        name: httpd
        state: present

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Install Git
      package:
        name: git
        state: present



    - name: Install Python and pip
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install Gunicorn
      pip:
        name: gunicorn
        state: present

    - name: Create Flask systemd service
      template:
        src: /home/ec2-user/flask/bitcoinproject/flask.service
        dest: /etc/systemd/system/flaskapp.service

    - name: Reload systemd daemon
      become: true
      command: sudo systemctl daemon-reload

    - name: Start Flask App service
      become: true
      command: sudo systemctl start flaskapp.service
    
    - name: Enable Flask App service on boot
      become: true
      command: sudo systemctl enable flaskapp.service

